version: "3.7"
services:
  php-cli:
    build:
      context: php
      dockerfile: Dockerfile
      args:
        PUID: $PUID
        PGID: $PGID
        PHP_VERSION: $PHP_VERSION
        PHP_TYPE: cli
    image: botraisa-php-cli
    container_name: botraisa-php
    command: symfony serve
    working_dir: /var/www/botraisa
    depends_on:
      - postgres
    volumes:
      - ..:/var/www/botraisa
      - ./php/php-ini-overrides.ini:/usr/local/etc/php/conf.d/zz-overrides.ini
    ports:
      - "8000:8000"
    networks:
      - botraisanetwork

  postgres:
    image: postgres:10
    container_name: botraisa-postgres
    volumes:
      - botraisa_postgres_volume:/var/lib/postgresql/data
      - ./psql/test-database.sh:/docker-entrypoint-initdb.d/test-database.sh
    environment:
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_DB: $POSTGRES_DB
    ports:
      - "${POSTGRES_EXTERNAL_PORT}:5432"
    networks:
      - botraisanetwork

volumes:
  botraisa_postgres_volume:

networks:
  botraisanetwork:
    name: botraisanetwork
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 10.19.19.0/24